In [215]:
# Examen diagnostico
# Carolina Obregon
# A01251983
# 4 de Enero 2021

In [216]:
smash = ['Mario', 'DK', 'Link', 'Samus', 'Yoshi', 'Kirby', 'Fox', 'Pikachu']

In [217]:
smash += ['Luigi', 'Ness', 'C. Falcon', 'Jifflypuff']

In [218]:
smash.append(['Metal Mario', 'Polygon Team', 'Master Hand'])

In [219]:
smash = smash[8:]

In [220]:
smash[:0] = ['Original Roster']

In [221]:
print(smash)

['Original Roster', 'Luigi', 'Ness', 'C. Falcon', 'Jifflypuff', ['Metal Mario', 'Polygon Team', 'Master Hand']]


In [222]:
import numpy as np

def null_matrix(N, M):
    a = np.zeros((N,M))
    return a

In [223]:
print(null_matrix(3,4))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [224]:
c = np.full((4,3),'?')
print(c)

[['?' '?' '?']
 ['?' '?' '?']
 ['?' '?' '?']
 ['?' '?' '?']]


In [225]:
x = np.full((4,3,2), '?')
x

array([[['?', '?'],
        ['?', '?'],
        ['?', '?']],

       [['?', '?'],
        ['?', '?'],
        ['?', '?']],

       [['?', '?'],
        ['?', '?'],
        ['?', '?']],

       [['?', '?'],
        ['?', '?'],
        ['?', '?']]], dtype='<U1')

In [226]:
mensualidad = {'Disney+': 7, 'Netflix': 8.99, 'Prime': 12.99}

In [227]:
try:
    del mensualidad['Disney+']
except KeyError:
    print("No Disney+ in mensualidad")


In [228]:
mensualidad['Blim'] = 109
mensualidad['Netflix'] = 139
mensualidad['Prime'] = 99

In [229]:
mensualidad['Tec'] = 20400

In [230]:
raw = np.array([[ 1, 2, 3, 4],
[ 5, 6, 7, 8],
[ 9, 10, 11, 12],
[13, 14, 15, 16]], dtype="object")

In [231]:
raw

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=object)

In [232]:
slice1 = raw[:2,1:3]

In [233]:
slice1

array([[2, 3],
       [6, 7]], dtype=object)

In [234]:
slice2 = raw[1:,2:]

In [235]:
slice2

array([[7, 8],
       [11, 12],
       [15, 16]], dtype=object)

In [236]:
features = raw[:,:3]

In [237]:
features

array([[1, 2, 3],
       [5, 6, 7],
       [9, 10, 11],
       [13, 14, 15]], dtype=object)

In [238]:
label = raw[:,3]

In [239]:
label

array([4, 8, 12, 16], dtype=object)

In [240]:
data = np.array(list(zip(features,label)))

<ipython-input-240-3a93aeb14f80>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data = np.array(list(zip(features,label)))


In [241]:
data

array([[array([1, 2, 3], dtype=object), 4],
       [array([5, 6, 7], dtype=object), 8],
       [array([9, 10, 11], dtype=object), 12],
       [array([13, 14, 15], dtype=object), 16]], dtype=object)

In [242]:
test = data[:1]

In [243]:
test

array([[array([1, 2, 3], dtype=object), 4]], dtype=object)

In [244]:
train = data[1:]

In [245]:
train

array([[array([5, 6, 7], dtype=object), 8],
       [array([9, 10, 11], dtype=object), 12],
       [array([13, 14, 15], dtype=object), 16]], dtype=object)

In [246]:
prob = .35 / .70
prob
# Probabilidad de que le guste Zelda es 50%

0.5

In [247]:
# no lo supe calcular

In [248]:
import sympy as sy
from sympy import *

x = sy.Symbol('x')
diff(x**3 * cos(x**2), x)
# −2𝑥4sin(𝑥2)+3𝑥2cos(𝑥2)

-2*x**4*sin(x**2) + 3*x**2*cos(x**2)

In [249]:
diff(x**2 * sin(x) + x**4, x)
# 4𝑥3+𝑥2cos(𝑥)+2𝑥sin(𝑥)

4*x**3 + x**2*cos(x) + 2*x*sin(x)

In [250]:
x, y, z = symbols('x y z', real=True)
func = x**3 + z*x**2 + x * z**2 + z**3
diff(func,x)

3*x**2 + 2*x*z + z**2